FROM navikey/raspbian-buster

COPY requirements.txt /opt/setup/requirements.txt
COPY ./lib/* /opt/lib/

WORKDIR /opt/setup
RUN apt-get update && apt-get -y install python3-dev gcc libc-dev g++ libzmq-dev musl-dev wget libusb-dev python3 python3-pip \
            libatlas-base-dev libusb-1.0-0-dev python3-opencv && rm -rf /var/lib/apt/lists/*
RUN pip3 install -r requirements.txt


WORKDIR /opt/source/server
CMD python3 main.py

