version: "3.9"
services:
  grafana:
    image: grafana/grafana:8.0.3
    network_mode: "host"
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json

  telegraf:
    image: telegraf-python:1.19.1
    network_mode: "host"
    volumes:
      - ./config/telegraf/:/etc/telegraf/
  
  ogs:
    image: ogs-core
    network_mode: "host"
    privileged: true # necessary to access usb devices
    volumes:    
    - type: bind
      source: ./source/
      target: /opt/source
    - type: bind
      source: ./config/ogs-core
      target: /opt/config
    # entrypoint: /bin/bash # only during development, removing this entrypoint override will cause the server to start automatically
  
  #gps:
  #  image: forcedinductionz/docker-gpsd
  #  privileged: true
  #  ports: 
  #    - 2947:2947

  #gps_simulator:
  #  image: forcedinductionz/docker-gpsd
  #  privileged: true
  #  ports: 
  #    - 2948:2948
  #  command: sh -c "gpsfake -p 2948 /opt/gps.log"
  #  volumes:
  #    - ./config/gpsfake/gps.log:/opt/gps.log
  




  