version: "3.9"
services:
  grafana:
    image: grafana/grafana
    network_mode: "host"
  influxd:
    image: influxdb:1.8
    network_mode: "host"
  telegraf:
    image: telegraf
    network_mode: "host"
    volumes:
        - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  ogs:
    image: ogs-core
    network_mode: "host"
    privileged: true