[server]
name = "server"
description = "OGS API"
host = "0.0.0.0"
port = 8000


[telegraf]
host = "localhost"
port = 8092


[mount]
name = "mount"

# calibration positions evenly spaced across hemisphere
calib_az_extended = [12.93, 45.21, 70.29, 77.12, 102.87, 109.70, 134.78, 167.06, 161.30, 136.26, 43.73, 18.69, 347.06, 314.78, 289.70, 282.87, 257.12, 250.29, 225.21, 192.93, 198.69, 223.73, 316.26, 341.30] # adapted from https://doi.org/10.1117/1.JATIS.4.3.034002
calib_el_extended = [29.37, 38.50, 53.84, 31.48, 31.48,  53.84,  38.48,  29.37,  52.50,  73.61,  73.60, 52.52, 29.37,  38.50,  53.84,  31.48,  31.48,  53.84,  38.50,  29.37,  52.52,  73.61,  73.61,  52.52]

# reduced set of calibration positions evenly spaced across hemisphere
calib_az = [45.21, 70.29, 77.12, 109.70, 134.78, 136.26, 18.69,  314.78, 289.70,  257.12, 250.29, 225.21,  198.69, 223.73, 316.26, 341.30] # adapted from https://doi.org/10.1117/1.JATIS.4.3.034002
calib_el = [38.50, 53.84, 31.48, 53.84,  38.48,  73.61,  52.52,  38.50,  53.84,   31.48,  53.84,  38.50,   52.52,  73.61,  73.61,  52.52]

# test set of calibration positions evenly spaced across hemisphere
calib_az_test = [0, 90, 18, 270]
calib_el_test = [30, 30, 60, 60]
use_test_calib = false

lat = 50.0
lon = 5.0
alt = 40.3

    [mount.azimuth]
    name = "azimuth"
    poll_interval = 10.0
    publish_interval = 0.05 # send data at 20 Hz to the dashboards
    limit_min = -180
    limit_max = 540
    target_threshold_trajectory = 0.1 # below this threshold in degrees, we are on-target
    target_threshold_offaxis = 0.02 # below this threshold in degrees, we are on-target

        [mount.azimuth.axis_parameters]
        4 = 140000 #maximum positioning speed
        5 = 75000 #maximum acceleration
        15 = 75000 #accelration A1
        16 = 100000 #velocity V1
        17 = 75000 #deceleration from max speed to v1
        18 = 75000 #deceleration between V1 and stop
        19 = 1 #start velocity
        20 = 10 #stop velocity

        6 = 128 # Maximum current
        7 = 16 # Standby current
        140 = 6 # Microstep Resolution
        160 = 0 # Step interpolation
        161 = 0 # Double step enable
        193 = 1 # Reference search mode
        202 = 200 # Motor fullstep resolution
        204 = 0 # Freewheeling mode
        212 = 0 # Maximum internal encoder deviation [encoder steps]
        181 = 180000 # if motor speed is below 1 degree per second and there is a stall, dont stop the motor
        214 = 0 # Power down delay [10ms]

        217 = 32768 # External encoder resolution [cpr]
        218 = 0 # Maximum external encoder deviation
        251 = 1 # Reverse shaft
        254 = 0 # Step/direction mode


        # stealthChop
        186 = 100000  # pwm threshold speed
        188 = 128  # pwm amplitude
        187 = 10  # pwm grad
        191 = 0  # pwm frequency
        192 = 1  # pwm autoscale

        # spreadCycle
        163 = 0  # spreadCycle/classic chopper
        167 = 3  # TOff
        166 = 7  # hysteresis start (offset)
        165 = 2  # hysteresis end
        162 = 2  # blank time
        184 = 0  # random TOff

        # coolStep
        172 = 1  # hysteresis start
        182 = 15  # coolStep threshold speed

        # high speed
        22 = 7999774  # thigh threshold
        27 = 0  # high speed chopper
        28 = 0  # high speed fullstep

        [mount.azimuth.controller_parameters]

        looprate = 0.06 # slightly faster update rate for the inner position loop
        kp_controller = 0.92
        ki_controller = 0.4
        kd_controller = 0.0

        looprate_offaxis_controller = 0.1 # 10 Hz update rate for outer off-axis loop
        kp_offaxis_controller = 0.8
        ki_offaxis_controller = 0.5
        kd_offaxis_controller = 0.0
        windup_offaxis_controller = 2.0


    [mount.elevation]
    name = "elevation"
    poll_interval = 10.0
    publish_interval = 0.05 # send data at 20 Hz to the dashboards
    limit_min = -5
    limit_max = 95
    target_threshold_trajectory = 0.1 # below this threshold in degrees, we are on-target
    target_threshold_offaxis = 0.02 # below this threshold in degrees, we are on-target

        [mount.elevation.axis_parameters]
        4 = 140000 #maximum positioning speed
        5 = 75000 #maximum acceleration
        15 = 75000 #accelration A1
        16 = 100000 #velocity V1
        17 = 75000 #deceleration from max speed to v1
        18 = 75000 #deceleration between V1 and stop
        19 = 1 #start velocity
        20 = 10 #stop velocity

        6 = 128 # Maximum current
        7 = 16 # Standby current
        140 = 6 # Microstep Resolution
        160 = 0 # Step interpolation
        161 = 0 # Double step enable
        193 = 1 # Reference search mode
        202 = 200 # Motor fullstep resolution
        204 = 0 # Freewheeling mode
        212 = 0 # Maximum internal encoder deviation [encoder steps]
        181 = 180000 # if motor speed is below 1 degree per second and there is a stall, dont stop the motor
        214 = 0 # Power down delay [10ms]

        217 = 32768 # External encoder resolution [cpr]
        218 = 0 # Maximum external encoder deviation
        251 = 0 # Reverse shaft
        254 = 0 # Step/direction mode


        # stealthChop
        186 = 100000  # pwm threshold speed
        188 = 128  # pwm amplitude
        187 = 10  # pwm grad
        191 = 0  # pwm frequency
        192 = 1  # pwm autoscale

        # spreadCycle
        163 = 0  # spreadCycle/classic chopper
        167 = 3  # TOff
        166 = 7  # hysteresis start (offset)
        165 = 2  # hysteresis end
        162 = 2  # blank time
        184 = 0  # random TOff

        # coolStep
        172 = 1  # hysteresis start
        182 = 15  # coolStep threshold speed

        # high speed
        22 = 7999774  # thigh threshold
        27 = 0  # high speed chopper
        28 = 0  # high speed fullstep

        [mount.elevation.controller_parameters]
        looprate = 0.06
        kp_controller = 0.92
        ki_controller = 0.4
        kd_controller = 0.0

        looprate_offaxis_controller = 0.1 # 10 Hz update rate for outer off-axis loop
        kp_offaxis_controller = 0.8
        ki_offaxis_controller = 0.5
        kd_offaxis_controller = 0.0
        windup_offaxis_controller = 2.0

[guider]
name = "guider"
id = "A" # id stored in the camera
streamport = 5555
streamhost = "0.0.0.0"
focal = 240.0 # focal length in mm
pitch_x  = 0.0024 # x pixel pitch in mm
pitch_y  = 0.0024 # y pixel pitch in mm
bandwidth = 80
exposure = 180000
gain = 350
whitebalance_blue = 99
whitebalance_red = 50
gamma = 50
flip = 1
b_highspeed = true
b_hwbin = true
startx = 0
starty = 0
width = 720
height = 520
offaxisetpoint_x = 0 # offaxis setpoint for target tracking in horizontal direction
offaxisetpoint_y = 0 # offaxis setpoing for target tracking in vertical direction
bins = 4
transport_compression = 95
fitstorage_dir = "/opt/data/fits/"
polinterval = 10.0
publish_interval = 1.0

b_object_detection_enabled = true
blob_minthreshold = 40
blob_maxthreshold = 255
blob_thresholdstep = 5
blob_color = 255
b_blob_filterbyarea = true
b_blob_filterbycircularity = true
b_blob_filterbyconvexity = false
b_blob_filterbyinertia = true
blob_minarea = 5
blob_mininertiaratio = 0
blob_maxinertiaratio = 1


[imager]
name = "imager"
id = "B" # id stored in the camera
streamport = 5556
streamhost = "0.0.0.0"
focal = 3750.0 # focal length in mm
pitch_x  = 0.0024 # x pixel pitch in mm
pitch_y  = 0.0024 # y pixel pitch in mm
bandwidth = 50
exposure = 2000
gain = 350
whitebalance_blue = 99
whitebalance_red = 50
gamma = 50
flip = 1
b_highspeed = false
b_hwbin = true
startx = 0
starty = 0
width = 800
height = 520
offaxisetpoint_x = 0 # offaxis setpoint for target tracking in horizontal direction
offaxisetpoint_y = 0 # offaxis setpoing for target tracking in vertical direction
bins = 1
transport_compression = 85
fitstorage_dir = "/opt/data/fits/"
polinterval = 10.0
publish_interval = 1.0

b_object_detection_enabled = false
blob_minthreshold = 40
blob_maxthreshold = 255
blob_thresholdstep = 5
blob_color = 255
b_blob_filterbyarea = true
b_blob_filterbycircularity = true
b_blob_filterbyconvexity = false
b_blob_filterbyinertia = true
blob_minarea = 5
blob_mininertiaratio = 0
blob_maxinertiaratio = 1


[object]
name = "object"
publish_interval = 1.0

